# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_lda <- function(mt, k, max_iter, alpha, beta, seeds, words, random, verbose) {
    .Call(`_seededlda_cpp_lda`, mt, k, max_iter, alpha, beta, seeds, words, random, verbose)
}

cpp_lda0 <- function(mt, k, max_iter, alpha, beta, seeds, words, random, verbose) {
    .Call(`_seededlda_cpp_lda0`, mt, k, max_iter, alpha, beta, seeds, words, random, verbose)
}

